apiVersion: v1
kind: Service
metadata:
  name: name-list-old
  labels:
    app: name-list-old
spec:
  type: LoadBalancer
  ports:
    - name: http-port
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: name-list-old

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-list-old
spec:
  selector:
    matchLabels:
      app: name-list-old
  replicas: 1
  template:
    metadata:
      labels:
        app: name-list-old
    spec:
      containers:
        - name: name-list-old
          image: tasyuminahito/name_list:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred
