apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{name}}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: {{name}}
  labels:
    app: {{name}}
spec:
  type: LoadBalancer
  ports:
    - name: http-port
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: {{name}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{name}}
spec:
  selector:
    matchLabels:
      app: {{name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{name}}
    spec:
      containers:
        - name: {{name}}
          image: {{image}}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: values-storage
              mountPath: /app/data
      volumes:
        - name: values-storage
          persistentVolumeClaim:
            claimName: {{name}}-pvc
      imagePullSecrets:
        - name: regcred


